// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var History = /* module */[];

var Connection = /* module */[];

exports.History = History;
exports.Connection = Connection;
/* No side effect */
